services:
  - type: web
    name: slidemissa-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    autoDeploy: true
